name: Step 6 - Pull Request and Merge

description: |
  Crea un Pull Request del branch de ejercicio a main y haz merge automáticamente al completar el ejercicio.

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_merge:
    name: Auto-merge exercise branch to main
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable auto-merge for PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "¡Felicidades! El ejercicio ha sido completado y el branch fue fusionado a main."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
